---
kind: pipeline
type: docker
name: BUILD-TEST
steps:
  - name: Build_Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/ddns-ipv64
      tags: latest
      dry_run: true

trigger:
  branch:
  - master
  event:
  - custom
  - push
  # - pull_request

---
kind: pipeline
type: docker
name: BUILD-Dockerhub
steps:
  - name: Build_Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password: 
        from_secret: DOCKER_PASS    
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/ddns-ipv64
      tags: v0.1.7,latest
      # auto_tag: true
      # auto_tag_suffix: v0.1.7

trigger:
  branch:
  - master
  event:
  - custom
  # - push
  # - pull_request

depends_on:
  - BUILD-TEST

---
kind: pipeline
type: docker
name: BUILD-TEST-DEV
steps:
  - name: Build_Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/ddns-ipv64
      tags: dev
      dry_run: true

trigger:
  branch:
  - development
  event:
  - custom
  # - push
  # - pull_request

---
kind: pipeline
type: docker
name: BUILD-Dockerhub-DEV
steps:
  - name: Build_Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password: 
        from_secret: DOCKER_PASS    
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/ddns-ipv64
      tags: dev
      # auto_tag: true
      # auto_tag_suffix: dev

trigger:
  branch:
  - development
  event:
  - custom
  # - push
  # - pull_request

depends_on:
  - BUILD-TEST-DEV
