services:
  ddns:
    image: rstrice/ddns64:latest
    container_name: ddns64
    restart: unless-stopped
    hostname: ddns64
    environment:
      - KEY
      - DOMAIN
    volumes:
      - /etc/localtime:/etc/localtime:ro

