services:
  ddns:
    image: rstrice/ddns-ipv64:latest
    container_name: ddns-ipv64
    restart: unless-stopped
    hostname: ddns-ipv64
    environment:
      - CRON_TIME
      - CRON_TIME_DIG
      - DOMAIN_KEY
      - DOMAIN_IPV64
      # Erweiterte Optionen (optional):
      # - "DOMAIN_IPV64=deine-domain.ipv64.net,deine-domain.ipv64.de"
      # - "DOMAIN_PRAEFIX_YES=yes"
      # ⚠️ Hier bitte nur ein DOMAIN PRAEFIX (subdomain) eintragen (ersetzen) ⚠️
      # - "DOMAIN_PRAEFIX=ddns"
      # IPv6/IPv4 Kontrolle:
      # - "IPV6_ENABLED=yes"
      # - "IPV4_ENABLED=yes"
      # Weitere Optionen:
      # - "IP_CHECK=yes"
      # - "SHOUTRRR_URL="
      # - "SHOUTRRR_SKIP_TEST=no"
      # - "NAME_SERVER=ns1.ipv64.net"
      # - "NETWORK_CHECK=yes"
      # - "CURL_USER_AGENT=DDNS-Updater-IPv64"
      # Log-Rotation:
      # - "MAX_FILES=10"
      # - "MAX_LINES=1000"
      # Benutzer-/Gruppen-IDs:
      # - "PUID=1000"
      # - "PGID=1000"
